# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\eric6\OperateM.ui'
#
# Created: Thu Apr 27 23:53:01 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(600, 400)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 239, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 239, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 239, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 239, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        Dialog.setAutoFillBackground(False)
        Dialog.setSizeGripEnabled(True)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(390, 360, 191, 21))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.groupBox_select = QtGui.QGroupBox(Dialog)
        self.groupBox_select.setGeometry(QtCore.QRect(10, 10, 571, 51))
        self.groupBox_select.setObjectName(_fromUtf8("groupBox_select"))
        self.label = QtGui.QLabel(self.groupBox_select)
        self.label.setGeometry(QtCore.QRect(30, 20, 91, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit_cx = QtGui.QLineEdit(self.groupBox_select)
        self.lineEdit_cx.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.lineEdit_cx.setObjectName(_fromUtf8("lineEdit_cx"))
        self.groupBox_selecttype = QtGui.QGroupBox(self.groupBox_select)
        self.groupBox_selecttype.setGeometry(QtCore.QRect(300, 10, 251, 31))
        self.groupBox_selecttype.setObjectName(_fromUtf8("groupBox_selecttype"))
        self.radioButton_xm = QtGui.QRadioButton(self.groupBox_selecttype)
        self.radioButton_xm.setGeometry(QtCore.QRect(50, 10, 51, 16))
        self.radioButton_xm.setObjectName(_fromUtf8("radioButton_xm"))
        self.radioButton_dq = QtGui.QRadioButton(self.groupBox_selecttype)
        self.radioButton_dq.setGeometry(QtCore.QRect(110, 10, 51, 16))
        self.radioButton_dq.setObjectName(_fromUtf8("radioButton_dq"))
        self.radioButton_bz = QtGui.QRadioButton(self.groupBox_selecttype)
        self.radioButton_bz.setGeometry(QtCore.QRect(170, 10, 71, 16))
        self.radioButton_bz.setObjectName(_fromUtf8("radioButton_bz"))
        self.pushButton_cx = QtGui.QPushButton(self.groupBox_select)
        self.pushButton_cx.setGeometry(QtCore.QRect(230, 18, 61, 23))
        self.pushButton_cx.setObjectName(_fromUtf8("pushButton_cx"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(140, 70, 441, 271))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 401, 221))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_xm = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_xm.setObjectName(_fromUtf8("lineEdit_xm"))
        self.gridLayout.addWidget(self.lineEdit_xm, 0, 1, 1, 1)
        self.lineEdit_xb = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_xb.setObjectName(_fromUtf8("lineEdit_xb"))
        self.gridLayout.addWidget(self.lineEdit_xb, 0, 3, 1, 1)
        self.lineEdit_tel = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_tel.setObjectName(_fromUtf8("lineEdit_tel"))
        self.gridLayout.addWidget(self.lineEdit_tel, 1, 3, 1, 1)
        self.lineEdit_email = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_email.setObjectName(_fromUtf8("lineEdit_email"))
        self.gridLayout.addWidget(self.lineEdit_email, 3, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.lineEdit_nl = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_nl.setObjectName(_fromUtf8("lineEdit_nl"))
        self.gridLayout.addWidget(self.lineEdit_nl, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.lineEdit_gz = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_gz.setObjectName(_fromUtf8("lineEdit_gz"))
        self.gridLayout.addWidget(self.lineEdit_gz, 3, 1, 1, 1)
        self.lineEdit_dz = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_dz.setObjectName(_fromUtf8("lineEdit_dz"))
        self.gridLayout.addWidget(self.lineEdit_dz, 2, 1, 1, 3)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.textEdit_bz = QtGui.QTextEdit(self.gridLayoutWidget)
        self.textEdit_bz.setObjectName(_fromUtf8("textEdit_bz"))
        self.gridLayout.addWidget(self.textEdit_bz, 5, 1, 1, 3)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.radioButton_custtip = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_custtip.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout.addWidget(self.radioButton_custtip, 6, 0, 1, 4)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(140, 350, 251, 31))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.radioButton_new = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_new.setGeometry(QtCore.QRect(70, 10, 60, 16))
        self.radioButton_new.setObjectName(_fromUtf8("radioButton_new"))
        self.radioButton_modify = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_modify.setGeometry(QtCore.QRect(130, 10, 51, 16))
        self.radioButton_modify.setObjectName(_fromUtf8("radioButton_modify"))
        self.radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(190, 10, 51, 16))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 70, 120, 311))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.tableView = QtGui.QTableView(self.groupBox_3)
        self.tableView.setGeometry(QtCore.QRect(10, 20, 101, 281))
        self.tableView.setObjectName(_fromUtf8("tableView"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "客户信息编辑", None))
        self.groupBox_select.setTitle(_translate("Dialog", "查询", None))
        self.label.setText(_translate("Dialog", "按姓名查询：", None))
        self.groupBox_selecttype.setTitle(_translate("Dialog", "按类型", None))
        self.radioButton_xm.setText(_translate("Dialog", "姓名", None))
        self.radioButton_dq.setText(_translate("Dialog", "地区", None))
        self.radioButton_bz.setText(_translate("Dialog", "备注信息", None))
        self.pushButton_cx.setText(_translate("Dialog", "查询", None))
        self.groupBox.setTitle(_translate("Dialog", "客户明细信息", None))
        self.label_2.setText(_translate("Dialog", "姓 名 ：", None))
        self.label_4.setText(_translate("Dialog", "年 龄 :", None))
        self.label_7.setText(_translate("Dialog", "工 作 ：", None))
        self.label_6.setText(_translate("Dialog", "地 址 ：", None))
        self.label_5.setText(_translate("Dialog", "电 话 ：", None))
        self.label_3.setText(_translate("Dialog", "性 别 ：", None))
        self.label_8.setText(_translate("Dialog", "电子邮件 ： ", None))
        self.label_9.setText(_translate("Dialog", "备注信息 ： ", None))
        self.radioButton_2.setText(_translate("Dialog", "是否添加客户提示", None))
        self.groupBox_2.setTitle(_translate("Dialog", "功能选择 ", None))
        self.radioButton_new.setText(_translate("Dialog", "新增", None))
        self.radioButton_modify.setText(_translate("Dialog", "修改", None))
        self.radioButton.setText(_translate("Dialog", "删除", None))
        self.groupBox_3.setTitle(_translate("Dialog", "查询结果", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

